name: Add comment to PR with environment links.
on:
  pull_request:
    types:
      - opened
jobs:
  Post-PR-Env-Links:
    if: ${{ github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set PR Number
        id: set_pr_number
        run: echo "::set-output name=pr_number::${{ github.event.number }}"
      - uses: actions/github-script@v6
        with:
          script: ${{ include('label-template.yml').update_pr_content }}
        env:
          pr_number: ${{ steps.set_pr_number.outputs.pr_number }}
