name: Add comment to PR with environment links.
on:
  pull_request:
    types:
      - opened
jobs:
  Post-PR-Env-Links:
    if: ${{ github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Badges
        run: |
          chmod +x update_badges.sh
          ./update_badges.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
