name: Add comment to PR with environment links.
on:
  pull_request:
    types:
      - opened
jobs:
  Post-PR-Env-Links:
    if: ${{ github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const updatePrBody = require('.github/workflows/update-pr-body.js');
            const newBody = updatePrBody(context.payload.pull_request.number);

            if (context.payload.pull_request.body == null || !context.payload.pull_request.body.includes(badges)) {
              github.rest.pulls.update({
                pull_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: badges + context.payload.pull_request.body
              })
            } else {
              console.log('Badges already exist for this PR');
            }
