name: Auto Create Pull Request and Add Team Reviewers

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow on

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up date
        # if: steps.verify-changed-files.outputs.files_changed == 'true'
        id: date
        run: echo "::set-output name=date::$(date +'%m-%d-%Y')"

      # - name: Install github cli
      #   run: |
      #     type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
      #     curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
      #     && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
      #     && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
      #     && sudo apt update \
      #     && sudo apt install gh -y

      - name: Find and Close PR
        run: |
          current_day_of_week=$(date +'%u')
          if [ "$current_day_of_week" == "1" ]; then
            branch_name="atc-ui-update-$(date -d 'last friday' +'%m-%d-%Y')"
          else
            branch_name="atc-ui-update-$(date -d 'yesterday' +'%m-%d-%Y')"
          fi

          pr_number=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls?q=head:${branch_name}" | jq -r '.[0].number')

          if [ "$pr_number" != "null" ]; then
              echo "Pull request number: #$pr_number"
              
              pr_branch_name=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number" | jq -r '.head.ref')
              if [ "$pr_branch_name" == "$branch_name" ]; then
                  echo "PR branch name matches: $pr_branch_name"
                  echo "Closing PR #$pr_number"
                  curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" -d '{"state": "closed"}' "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number"

                  echo "Deleting branch $branch_name"
                  curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$branch_name"
              else
                  echo "PR branch name does not match: $pr_branch_name"
              fi
          else
              echo "No PR found with branch name $branch_name"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Team Members
        id: get_members
        run: |
          organization="toanla2002"
          team_slug="testautoadd"

          # Get team_slug ID
          team_id=$(curl -s "https://api.github.com/orgs/$organization/teams/$team_slug" -H "Authorization: token ${{ secrets.REPO_SCOPED_TOKEN }}" | jq -r '.id')

          if [ -n "$team_id" ]; then
            # Get list member
            members_json=$(curl -s "https://api.github.com/teams/$team_id/members" -H "Authorization: token ${{ secrets.REPO_SCOPED_TOKEN }}")
            members=$(echo "$members_json" | jq -r '.[].login')

            # Print list member
            echo "Team Members for $team_slug in $organization: $members"

            echo "::set-output name=list_reviewers::$members"
          else
            echo "Unable to retrieve team ID for $team_slug"

            # Add fallback value
            members="MacTheNhan lqtoan20 HoangHai"
          fi

      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Create pull request
        # if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: peter-evans/create-pull-request@v5
        id: cpr
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          commit-message: Update package version
          title: atc-ui update ${{ steps.date.outputs.date }}
          # labels: atc-ui update
          branch: atc-ui-update-${{ steps.date.outputs.date }}
          reviewers: ${{ steps.get_members.outputs.list_reviewers }}
          base: "main"

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          # echo "Team member - ${{ steps.get_members.outputs.list_reviewers }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
