name: Auto Create Pull Request and Add Team Reviewers

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow on

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Find and close PR update atc-ui not merge
        run: |
          branch_name="new-feature"  # Thay thế bằng tên nhánh bạn muốn tìm
          pr_number=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls?q=base:${branch_name}" | jq -r '.[0].number')
          if [ -n "$pr_number" ]; then
              echo "Found PR with branch name $branch_name: #$pr_number"

              echo "Closing PR #$pr_number"
              curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" -d '{"state": "closed"}' "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number"

              echo "Deleting branch $branch_name"
              curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$branch_name"
          else
              echo "No PR found with branch name $branch_name"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: Auto-generated Pull Request
          branch: new-feature
          base: main # Change this to your desired base branch
          commit-message: "Auto-generated changes"
          # reviewers: ${members}
          token: ${{ secrets.GITHUB_TOKEN }}
          # team-reviewers: |
          #   teams/testautoadd
