name: Auto Create Pull Request and Add Team Reviewers

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow on

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up date
        # if: steps.verify-changed-files.outputs.files_changed == 'true'
        id: date
        run: echo "::set-output name=date::$(date +'%m-%d-%Y')"

      # - name: Find and Close PR
      #   run: |
      #     current_day_of_week=$(date +'%u')
      #     if [ "$current_day_of_week" == "1" ]; then
      #       branch_name="atc-ui-update-$(date -d 'last friday' +'%m-%d-%Y')"
      #     else
      #       branch_name="atc-ui-update-$(date -d 'yesterday' +'%m-%d-%Y')"
      #     fi

      #     pr_number=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls?q=head:${branch_name}" | jq -r '.[0].number')

      #     if [ "$pr_number" != "null" ]; then
      #         echo "Pull request number: #$pr_number"

      #         pr_branch_name=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number" | jq -r '.head.ref')
      #         if [ "$pr_branch_name" == "$branch_name" ]; then
      #             echo "PR branch name matches: $pr_branch_name"
      #             echo "Closing PR #$pr_number"
      #             curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" -d '{"state": "closed"}' "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number"

      #             echo "Deleting branch $branch_name"
      #             curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$branch_name"
      #         else
      #             echo "PR branch name does not match: $pr_branch_name"
      #         fi
      #     else
      #         echo "No PR found with branch name $branch_name"
      #     fi
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Close Stale Pull Requests
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       const dateRegExp = /atc-ui-update-\d{2}-\d{2}-\d{4}/;
      #       const today = new Date().toLocaleDateString('en-US', { month: '2-digit', day: '2-digit', year: 'numeric' });

      #       const { data: pullRequests } = await github.rest.pulls.list({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         state: 'open',
      #       });

      #       for (const pr of pullRequests) {
      #         const branchName = pr.head.ref;

      #         if (dateRegExp.test(branchName)) { // Kiểm tra nếu tên branch phù hợp với regex
      #           const match = dateRegExp.exec(branchName);
      #           const branchDate = new Date(match[0]).toLocaleDateString('en-US', {
      #             month: '2-digit',
      #             day: '2-digit',
      #             year: 'numeric',
      #           });

      #           if (branchDate !== today) {
      #             console.log(`Closing PR: ${pr.number}`);
      #             await github.rest.pulls.update({
      #               owner: context.repo.owner,
      #               repo: context.repo.repo,
      #               pull_number: pr.number,
      #               state: 'closed',
      #             });
      #           }
      #         }
      #       }
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List and Cleanup Pull Requests
        uses: actions/github-script@v6
        with:
          script: |
            // Define the branch name format
            const dateRegExp = /atc-ui-update-\d{2}-\d{2}-\d{4}/;

            // Get the current date in the format xx-xx-xxxx
            const today = new Date().toLocaleDateString('en-US', { month: '2-digit', day: '2-digit', year: 'numeric' });

            // List open pull requests
            const pullRequests = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
            });

            // Process each open pull request
            for (const pr of pullRequests.data) {
              const branchName = pr.head.ref;

              if (dateRegExp.test(branchName)) {
                const match = dateRegExp.exec(branchName);
                const branchDate = new Date(match[0]).toLocaleDateString('en-US', {
                  month: '2-digit',
                  day: '2-digit',
                  year: 'numeric',
                });

                if (branchDate !== today) {
                  console.log(`Closing PR: ${pr.number}`);

                  await github.rest.pulls.update({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr.number,
                    state: 'closed',
                  });
                }
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        id: cpr
        with:
          commit-message: Update package version
          title: atc-ui update ${{ steps.date.outputs.date }}
          labels: atc-ui update
          branch: atc-ui-update-${{ steps.date.outputs.date }}
          delete-branch: true
          reviewers: MacTheNhan
          body: ./pull-request-template.md
          base: "main"

      - name: Update PR Body
        if: ${{ steps.cpr.outputs.pull-request-number }}
        uses: actions/github-script@v6
        with:
          script: |
            const createBadges = require('./.github/workflows/badges_template.js');
            const badges = createBadges(${{ steps.cpr.outputs.pull-request-number }});
            const fs = require('fs');
            const templateContent = fs.readFileSync('.github/pull-request-template.md', 'utf-8');
            const newBody = badges + '<div>This pull request was automatically created on ${{ steps.date.outputs.date }}</div>' + '\n\n' + templateContent

            github.rest.pulls.update({
              pull_number: ${{ steps.cpr.outputs.pull-request-number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: newBody
            })

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          # echo "Team member - ${{ steps.get_members.outputs.list_reviewers }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
