name: Get Team Members

on: [workflow_dispatch] # Trigger manually or adjust as needed

jobs:
  get-team-members:
    runs-on: ubuntu-latest # Replace with your preferred runner if needed
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 12 # Adjust if required

      - run: npm install @octokit/rest@18.10.0

      - run: |
          node -e "
            const { Octokit } = require('@octokit/rest');
            const octokit = new Octokit({
              auth: 'token ' + process.env.GITHUB_TOKEN,
              headers: {
                'Accept': 'application/vnd.github.v3+json',
              },
            });

            const orgName = 'toanla2002';
            const teamSlug = 'testautoadd';

            async function getTeamMembers() {
              try {
                const members = await octokit.teams.listMembersInOrg({
                  org: orgName,
                  team_slug: teamSlug,
                });

                console.log('Team members:', members.data);

                // Further process the member data as needed
              } catch (error) {
                console.error('Error fetching team members:', error);
                // Handle errors appropriately
              }
            }

            getTeamMembers();
          "
